#!/bin/bash

ln -s ~/dotfiles/git ~/.gitconfig
ln -s ~/dotfiles/tmux ~/.tmux.conf
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
ln -s ~/dotfiles/vis.zsh-theme ~/.oh-my-zsh/custom/themes/vis.zsh-theme
ln -s ~/dotfiles/zsh ~/.zshrc
chsh -s $(which zsh)
